name: Create Recipe
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Recipe name'
        required: true
        type: string
      description:
        description: 'Recipe description'
        required: true
        type: string
      steps:
        description: 'Number of steps'
        required: true
        type: string
      username:
        description: 'Username'
        required: true
        type: string
      user_secret:
        description: 'User secret'
        required: true
        type: string

env:
  RECIPE_NAME: ${{ github.event.inputs.name }}
  RECIPE_DESCRIPTION: ${{ github.event.inputs.description }}
  RECIPE_STEPS: ${{ github.event.inputs.steps }}
  USERNAME: ${{ github.event.inputs.username }}
  USER_SECRET: ${{ github.event.inputs.user_secret }}

jobs:
  create-recipe:
    name: Create Recipe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo inputs
        run: |
          echo "Recipe name: $RECIPE_NAME"
          echo "Recipe description: $RECIPE_DESCRIPTION"
          echo "Number of steps: $RECIPE_STEPS"
          echo "Username: $USERNAME"

      - name: Create a unique string
        run: |
          USER_ID=$(echo -n "$USERNAME$USER_SECRET" | md5sum | cut -d' ' -f1)
          echo "Secret: $USER_ID"
          echo "USER_ID=$USER_ID" >> $GITHUB_ENV

      - name: Register User
        run: |
          URL_SAFE_USERNAME=$(echo "$USERNAME" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_\-\.' | tr -s '_' | sed 's/ /_/g')
          echo "$USER_ID" > $URL_SAFE_USERNAME
          mkdir -p users/$USER_ID
          echo "$URL_SAFE_USERNAME" > users/$USER_ID/name

      - name: Create recipe
        run: |
          mkdir -p recipes/$USER_ID
          URL_SAFE_RECIPE_NAME=$(echo "$RECIPE_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_\-\.' | tr -s '_' | sed 's/ /_/g')
          echo "# $RECIPE_NAME
          ### $RECIPE_DESCRIPTION

          Steps:
          $RECIPE_STEPS
          " > recipes/$USER_ID/$URL_SAFE_RECIPE_NAME.md

          # list all markdown files in the recipes directory
          ls recipes/$USER_ID | sed 's/\.md$//' | tr '\n' ' ' > recipes/$USER_ID/index.list

      - name: Commit changes
        run: |
          ls recipes/$USER_ID
          cat recipes/$USER_ID/index.list
          cat users/$USER_ID/name