name: Create Recipe

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Recipe name'
        required: true
        type: string
      steps:
        description: 'Number of steps'
        required: true
        type: string
      username:
        description: 'Username'
        required: true
        type: string
      user_secret:
        description: 'User secret'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.name }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  create-recipe:
    name: Create Recipe
    runs-on: ubuntu-latest
    env:
      RECIPE_NAME: ${{ github.event.inputs.name }}
      RECIPE_STEPS: ${{ github.event.inputs.steps }}
      USER_NAME: ${{ github.event.inputs.username }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create a unique string
        env:
          USER_SECRET: ${{ github.event.inputs.user_secret }}
        run: |
          echo "::add-mask::$USER_SECRET"
          USER_ID=$(echo -n "$USER_NAME $USER_SECRET" | sha256sum | cut -d' ' -f1)
          echo "USER_ID=$USER_ID" >> $GITHUB_ENV

      - name: Register User
        run: |
          URL_SAFE_USERNAME=$(echo "$USER_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_\-\.' | tr -s '_' | sed 's/ /_/g')
          mkdir -p users/$USER_ID
          echo "$URL_SAFE_USERNAME" > users/$USER_ID/name

      - name: Create recipe
        run: |
          mkdir -p recipes/$USER_ID
          URL_SAFE_RECIPE_NAME=$(echo "$RECIPE_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_\-\.' | tr -s '_' | sed 's/ /_/g')
          echo "# $RECIPE_NAME

          $RECIPE_STEPS" > recipes/$USER_ID/$URL_SAFE_RECIPE_NAME.md

          # list all markdown files in the recipes directory
          ls -I "*.list" recipes/$USER_ID | sort  > recipes/$USER_ID/index.list

      - name: Commit changes
        continue-on-error: true
        run: |
          git config --global user.name 'The Octocat'
          git config --global user.email 'octocat@github.com'
          git add .
          git commit -m "Add $RECIPE_NAME for $USERNAME"
          git push
